import { type ProjectType } from "../types/projectType";

export const PROJECTS_DATA: ProjectType[] = [
  {
    id: "1",
    title: "project.title.1",
    category: "fullstack",
    description: "project.description.1",
    tags: ["PHP", "MySQL", "Outro"],
    imageUrl: "https://github.com/ddmdros.png",
    docsUrl: "/docs/gram-panchayat",
    githubUrl: "https://github.com/ddmdros/gram-panchayat",
    projectUrl: "",
    isFeatured: true,
  },
  {
    id: "2",
    title: "project.title.1",
    category: "backend",
    description: "project.description.1",
    tags: ["PHP", "MySQL", "Outro"],
    imageUrl: "https://github.com/ddmdros.png",
    docsUrl: "/docs/gram-panchayat",
    githubUrl: "https://github.com/ddmdros/gram-panchayat",
    projectUrl: "",
    isFeatured: true,
  },
  {
    id: "3",
    title: "project.title.1",
    category: "fullstack",
    description: "project.description.1",
    tags: ["PHP", "MySQL", "Outro"],
    imageUrl: "https://github.com/ddmdros.png",
    docsUrl: "/docs/gram-panchayat",
    githubUrl: "https://github.com/ddmdros/gram-panchayat",
    projectUrl: "",
    isFeatured: true,
  },
  {
    id: "4",
    title: "project.title.1",
    category: "fullstack",
    description: "project.description.1",
    tags: ["PHP", "MySQL", "Outro"],
    imageUrl: "https://github.com/ddmdros.png",
    docsUrl: "/docs/gram-panchayat",
    githubUrl: "https://github.com/ddmdros/gram-panchayat",
    projectUrl: "",
    isFeatured: true,
  },
];
