export const PROJECTS_DATA = [
  {
    id: 1,
    category: "Fullstack",
    title: "project.title.1",
    description: "project.description.1",
    tags: ["PHP", "MySQL", "Outro"],
    imageUrl: "https://github.com/ddmdros.png",
    docsUrl: "/docs/gram-panchayat",
    githubUrl: "https://github.com/ddmdros/gram-panchayat",
  },
  {
    id: 2,
    category: "Fullstack",
    title: "project.title.1",
    description: "project.description.1",
    tags: ["PHP", "MySQL", "Outro"],
    imageUrl: "https://github.com/ddmdros.png",
    docsUrl: "/docs/gram-panchayat",
    githubUrl: "https://github.com/ddmdros/gram-panchayat",
  },
  {
    id: 3,
    category: "Fullstack",
    title: "project.title.1",
    description: "project.description.1",
    tags: ["PHP", "MySQL", "Outro"],
    imageUrl: "https://github.com/ddmdros.png",
    docsUrl: "/docs/gram-panchayat",
    githubUrl: "https://github.com/ddmdros/gram-panchayat",
  },
  {
    id: 4,
    category: "Fullstack",
    title: "project.title.1",
    description: "project.description.1",
    tags: ["PHP", "MySQL", "Outro"],
    imageUrl: "https://github.com/ddmdros.png",
    docsUrl: "/docs/gram-panchayat",
    githubUrl: "https://github.com/ddmdros/gram-panchayat",
  },
];
